### ISSUE TITLE
rcon: Unable to connect to server

### ISSUE THREAD

**Issue by LM1LC3N7** [jacobtomlinson/docker-steam-insurgency#2]
Hello,

I'm using your scripts to create my own insurgency server and it works well. But when I open the console and type `rcon_password <PASSWORD>` and then `rcon status`, I get `Unable to connect to remote server (x.x.x.x:27015)`.

**insurgency/cfg/server.cfg**

```
rcon_password "admin"                       // RCon password
sv_rcon_log 1                                       // Log everything
sv_rcon_maxfailures 5                          // ban after 5 failures
sv_rcon_banpenalty 30                        // ban 10 minutes
```

**docker**
My docker container is running:

```
8290f14cbb78    Up 8 minutes        0.0.0.0:27015->27015/udp, 0.0.0.0:27016->27016/tcp             insurgency
```

**In game**
In game I open my console and type the following commands:

```
] rcon_password admin
] rcon status
Unable to connect to remote server (x.x.x.x:27015)
```

The `rcon status` provoque a game freeze during 1 second too.

**Comment by jacobtomlinson** [comment]
I'm glad this project was useful to you! I'm afraid I've noticed the same thing but haven't found a solution yet.

**Comment by LM1LC3N7** [comment]
I read somewhere that rcon use the 27020 port. But I didn't try it.

**Comment by LM1LC3N7** [comment]
I can confirm that it is working by openning the 27020 port.
