### ISSUE TITLE
Workshop 

### ISSUE THREAD

**Issue by DieterKoblenz** [jacobtomlinson/docker-steam-insurgency#3]
Is it possible to enable workshop support from a config file?

**Comment by jacobtomlinson** [comment]
Probably

**Comment by jimbo8098** [comment]
@DieterKoblenz can you give us an example of what you#re looking for there? Might visit it 🤷

**Comment by jacobtomlinson** [comment]
@jimbo8098 this issue was opened two years ago with no further activity. You may not get a response here.
